project:
  type: website

website:
  title: "TINYTOOLS"
  navbar:
    left:
      - people.qmd
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: blog
    # right:
    #   - icon: github
    #     href: https://github.com/tinytools-py/

  sidebar:
    - id: test
      contents:
        - projects/index.qmd
format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: true



